/* ============================
   TRANSITPAY - Monthly Billing
   Auto-generate PENDING receipts for all clients
   ============================ */

// ==================== GENERATE MONTHLY BILLS ====================
function generateMonthlyBills() {
    const monthEl = document.getElementById('billingMonth');
    const yearEl = document.getElementById('billingYear');
    if (!monthEl || !yearEl) return;

    const month = monthEl.value;
    const year = yearEl.value;
    if (!month || !year) {
        showToast('Please select a month and year', 'error');
        return;
    }

    const clients = (appData.clients || []).filter(c => c.monthlyRate && c.monthlyRate > 0);
    if (clients.length === 0) {
        showToast('No clients with a monthly rate set. Add a Monthly Rate to your clients first.', 'error');
        return;
    }

    let created = 0;
    let skipped = 0;

    clients.forEach(client => {
        // Check if a receipt already exists for this client/month/year
        const exists = (appData.receipts || []).some(r =>
            r.clientName === client.name &&
            r.month === month &&
            String(r.year) === String(year)
        );

        if (exists) {
            skipped++;
            return;
        }

        // Create PENDING receipt
        const receipt = {
            id: 'TPR-' + String(appData.nextReceiptNumber).padStart(5, '0'),
            type: 'monthly',
            clientName: client.name,
            clientPhone: client.phone || '',
            clientId: client.id,
            date: new Date().toISOString().split('T')[0],
            paymentStatus: 'Pending',
            month: month,
            year: parseInt(year),
            items: [{
                description: `Monthly Transport — ${month} ${year}`,
                amount: client.monthlyRate
            }],
            total: client.monthlyRate,
            createdAt: new Date().toISOString(),
            autoGenerated: true
        };

        appData.receipts.push(receipt);
        appData.nextReceiptNumber++;
        created++;

        if (typeof addAuditLog === 'function') {
            addAuditLog('created', 'receipt', `Auto-generated receipt ${receipt.id} for ${client.name} — RM ${client.monthlyRate.toFixed(2)} (${month} ${year})`, { id: receipt.id });
        }
    });

    if (created > 0) {
        saveAppData(appData);
        showToast(`✅ Generated ${created} receipt${created > 1 ? 's' : ''} as PENDING!${skipped > 0 ? ` (${skipped} already existed)` : ''}`, 'success');
    } else if (skipped > 0) {
        showToast(`All ${skipped} receipts for ${month} ${year} already exist.`, 'info');
    }

    loadUnpaidSummary();
    if (typeof loadReceipts === 'function') loadReceipts();
    if (typeof updateDashboard === 'function') updateDashboard();
}

// ==================== UNPAID SUMMARY ====================
function loadUnpaidSummary() {
    const container = document.getElementById('unpaidSummaryList');
    if (!container) return;

    const receipts = appData.receipts || [];

    // Get all PENDING or Unpaid receipts
    const unpaid = receipts.filter(r =>
        r.paymentStatus === 'Pending' || r.paymentStatus === 'Unpaid' || r.paymentStatus === 'Unable'
    );

    // Group by client
    const byClient = {};
    unpaid.forEach(r => {
        const key = r.clientName || 'Unknown';
        if (!byClient[key]) byClient[key] = [];
        byClient[key].push(r);
    });

    // Update summary badge
    const badge = document.getElementById('unpaidCount');
    if (badge) badge.textContent = unpaid.length;

    if (unpaid.length === 0) {
        container.innerHTML = `
            <div class="empty-state-mini" style="padding:2rem;text-align:center;">
                <div style="font-size:2.5rem;margin-bottom:0.5rem;">🎉</div>
                <p style="color:var(--text-muted);">All clients are paid up!</p>
            </div>
        `;
        return;
    }

    const totalOwed = unpaid.reduce((s, r) => s + r.total, 0);

    container.innerHTML = `
        <div style="padding:0.75rem 1rem;background:rgba(239,68,68,0.08);border-radius:8px;margin-bottom:1rem;display:flex;justify-content:space-between;align-items:center;">
            <span style="color:#fca5a5;font-weight:600;">Total Outstanding</span>
            <span style="font-family:var(--font-mono);font-weight:700;color:#f87171;font-size:1.1rem;">RM ${totalOwed.toFixed(2)}</span>
        </div>
        ${Object.entries(byClient).map(([name, recs]) => {
        const total = recs.reduce((s, r) => s + r.total, 0);
        return `
            <div class="unpaid-client-row">
                <div class="unpaid-client-info">
                    <strong>${name}</strong>
                    <span style="color:var(--text-muted);font-size:0.8rem;">${recs.length} receipt${recs.length > 1 ? 's' : ''} pending</span>
                </div>
                <div class="unpaid-client-actions">
                    <span style="font-family:var(--font-mono);font-weight:700;color:#fcd34d;">RM ${total.toFixed(2)}</span>
                    ${recs.map(r => `
                        <button class="btn btn-xs btn-success" onclick="markReceiptPaid('${r.id}')" title="Mark ${r.id} as Paid">
                            ✓ Mark ${r.id} Paid
                        </button>
                    `).join('')}
                </div>
            </div>
            `;
    }).join('')}
    `;
}

// ==================== MARK RECEIPT AS PAID ====================
function markReceiptPaid(receiptId) {
    const idx = (appData.receipts || []).findIndex(r => r.id === receiptId);
    if (idx === -1) return;

    appData.receipts[idx].paymentStatus = 'Paid';
    appData.receipts[idx].paidAt = new Date().toISOString();

    saveAppData(appData);
    showToast(`Receipt ${receiptId} marked as PAID ✅`, 'success');

    if (typeof addAuditLog === 'function') {
        addAuditLog('updated', 'receipt', `Marked ${receiptId} as PAID`, { id: receiptId });
    }

    loadUnpaidSummary();
    if (typeof loadReceipts === 'function') loadReceipts();
    if (typeof updateDashboard === 'function') updateDashboard();
}

// ==================== INIT BILLING SECTION ====================
function initMonthlyBilling() {
    const monthEl = document.getElementById('billingMonth');
    const yearEl = document.getElementById('billingYear');
    if (!monthEl || !yearEl) return;

    // Default to current month/year
    const now = new Date();
    const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    monthEl.value = months[now.getMonth()];
    yearEl.value = now.getFullYear();

    loadUnpaidSummary();
}
